# This is a basic workflow that is manually triggered

name: PR to Production

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: deployment_status

jobs:
    get-version:
        runs-on: ubuntu-latest
        outputs:
            API_VERSION: ${{ steps.package-version.outputs.API_VERSION }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - id: package-version
              run: echo "API_VERSION=$(jq -r .version package.json )" >> "$GITHUB_OUTPUT"

    create-pull-request:
        if: github.event.deployment_status.environment == 'benweare-dev' && github.event.deployment_status.state == 'success'
        runs-on: ubuntu-latest
        needs: [get-version]
        env:
            API_VERSION: ${{ needs.get-version.outputs.API_VERSION }}

        steps:
            - uses: actions/checkout@v4

            - name: 💬 Submit Pull Request to main\
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  # Configure and clone
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

                  # Create PR on server repo
                  gh pr create \
                  --body "AUTOMATED: Merge Development ${{ env.API_VERSION }} to Main." \
                  --title "CHORE: DEV -> PROD" \
                  --head "development" \
                  --base "main"
