# This is a basic workflow that is manually triggered

name: PR to Production

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: deployment_status

jobs:
    check-publish-ready:
        if: github.ref == 'refs/heads/development' && github.event.deployment_status.environment == 'benweare-dev' && github.event.deployment_status.state == 'success'
        uses: ./.github/workflows/code-quality.yml

    create-pull-request:
        if: github.ref == 'refs/heads/development' && github.event.deployment_status.environment == 'benweare-dev' && github.event.deployment_status.state == 'success'
        runs-on: ubuntu-latest
        needs: [check-publish-ready]

        steps:
            - uses: actions/checkout@v4

            - name: 💬 Submit Pull Request to main\
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  # Configure and clone
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

                  # Create PR on server repo
                  gh pr create \
                  --body "AUTOMATED: Merge Development to Main." \
                  --title "CHORE: DEV -> PROD" \
                  --head "development" \
                  --base "main"
