# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - development
            - '*'
    pull_request:
        branches:
            - main
            - development

jobs:
    check-publish-ready:
        uses: ./.github/workflows/code-quality.yml

    create-pull-request:
        runs-on: ubuntu-latest
        needs: [check-publish-ready]

        steps:
            - uses: actions/checkout@v4

            - name: 💬 Submit Pull Request to main
              #   if: github.ref == 'refs/heads/development'
              env:
                  GH_TOKEN: ${{ github.token }}
              run: |
                  # Configure and clone
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"


                  npm install lodash@latest

                  BRANCH_NAME="CHORE-TEST"
                  git checkout -b $BRANCH_NAME
                  git commit -am "CHORE: Test install update"
                  git push origin $BRANCH_NAME

                  # Create PR on server repo
                  gh pr create \
                  --body "AUTOMATED: Merge Development to Main." \
                  --title "CHORE: DEV -> PROD" \
                  --head "$BRANCH_NAME" \
                  --base "development"
