# This is a basic workflow that is manually triggered

name: Build and Deploy

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    check-publish-ready:
        uses: ./.github/workflows/code-quality.yml
